services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: wize-invoice-frontend:13.06.2025v1
    container_name: wize-invoice-frontend
    ports:
      - "3001:3000"
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=https://invoice-ai-api.octaprimetech.com
    networks:
      - invoice-ai-front-network

networks:
  invoice-ai-front-network:
    driver: bridge